name: Build Multi-Arch Docker Image

on:
  # Allow manual trigger, so that we can trigger the build from the GitHub Actions UI
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tier: [1, 2, 3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/tier${{ matrix.tier }}/Dockerfile
          push: true
          tags: wisdomwork/judge-tier-${{ matrix.tier }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
